# Generated by Django 5.0.6 on 2024-06-18 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='answer',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
