# Generated by Django 5.0.6 on 2024-06-18 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_graded_submission_subtask_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='graded_submission',
            name='task_id',
        ),
        migrations.AddField(
            model_name='graded_submission',
            name='submission_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.submission'),
            preserve_default=False,
        ),
    ]
