# Generated by Django 5.0.6 on 2024-06-18 11:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_graded_submission_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='graded_submission',
            name='submission_id',
        ),
        migrations.AddField(
            model_name='graded_submission',
            name='submission_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='graded_submission',
            name='submission_due_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='graded_submission',
            name='submission_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='graded_submission',
            name='submission_start_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
