# Generated by Django 5.0.6 on 2024-06-18 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_graded_submission_submission_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='graded_submission',
            name='task_id',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
