# Generated by Django 5.0.6 on 2024-06-28 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_task_file_name_task_file_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='file_upload',
            field=models.FileField(blank=True, null=True, upload_to='tasks/'),
        ),
    ]
