# Generated by Django 5.0.6 on 2024-06-29 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_task_subtasks_task_subtasks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='file_name',
        ),
        migrations.AddField(
            model_name='task',
            name='require_file',
            field=models.BooleanField(default=False),
        ),
    ]
