# Generated by Django 5.0.6 on 2024-06-16 06:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_classes'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='enrolled_classes', to=settings.AUTH_USER_MODEL),
        ),
    ]
